---@meta

---@class RGB
---@field public r number RED value
---@field public g number GREEN value 
---@field public b number BLUE value
---@field public opacity number OPACITY value from 0-1 range

---@class Theme
---@field public background_color RGB
---@field public outline_thickness number Thickness of the outline (border)
---@field public outline_color RGB Color of the outline (border)
---@field public text_color RGB Color of the text
---@field public selected_color RGB
---@field public font Font
---@field public font_size number

---@class Window
---@field public name string Name of the window
---@field public x number X position
---@field public y number Y position
---@field public width number Width of the window
---@field public height number Height of the window
---@field public theme Theme
---@field public enabled boolean If it's disabled
---@field public background_color RGB Background color of the window
---@field public children table Gets all objects below it (children, literally)

---@class Button
---@field public name string Name of the button
---@field public text string
---@field public x number X position
---@field public y number Y position
---@field public width number Width of the button
---@field public theme Theme
---@field public parent Window
---@field public height number Height of the button
---@field public enabled boolean If it's disabled
---@field public selectable boolean
---@field public click function Called when clicked
---@field private last_clicked_tick number please don't change this manually

---@class Slider
---@field public name string The name of the slider
---@field public x number
---@field public y number
---@field public width number The width (horizontal length)
---@field public height number The height (vertical length)
---@field public theme Theme The theme
---@field public click function The function called when clicked
---@field public parent Window The window above it
---@field public min number The lowest the slider can go
---@field public max number The highest the slider can go
---@field public value number The current value
---@field private percent number
---@field public enabled boolean If it's enabled
---@field public selectable boolean If you can click on the slider

---@class Checkbox
---@field public name string The name of the checkbox
---@field public x number
---@field public y number
---@field public width number The width (horizontal length)
---@field public height number The height (vertical length)
---@field public checked boolean If it's true or false
---@field public selectable boolean If you can click on the slider
---@field public theme Theme The theme
---@field public enabled boolean If it's enabled
---@field public size number

---@class Combobox
---@field public name string
---@field public parent Window
---@field public x number
---@field public y number
---@field public combbuttons table
---@field public width number
---@field public height number
---@field public theme Theme
---@field public items table
---@field public selected_item number
---@field public displaying_items boolean
---@field public enabled boolean
---@field public selectable boolean

---@class Text
---@field public x number
---@field public y number
---@field public text string
---@field public color RGB
---@field public font Font

---@class Round_Button
---@field public name string The button's name
---@field public text string The button's text
---@field public parent Window the button's parent Window
---@field public x number
---@field public y number
---@field public width number Horizontal length
---@field public height number Vertical length
---@field public click function
---@field public theme Theme
---@field public selectable boolean
---@field public enabled boolean
---@field public roundness number How "round" the round button is

---@class Command
---@field required_parameters table The required parameters/arguments to run the command | example: {name = "string", players = "table"}
---@field callback function The function that is used when calling the command | example: con create-command hellomom
---@field description string The description of the command